---
- hosts: demo
  bedome: yes
  tasks:
    - name:  install a package
      action: yum name=httpd state=present
      when: ansible_os_family == "redhat"
    - name: Install package docker
      action: yum name=docker state=present
      when: ansible_os_family != "redhat"


  #ansible-playbook conditions_playbook.yaml 
  # skips if condition doesnt match
  # performs the changes when condition matches